use super::*;
use crate::test_source::Shared;

struct Temp(Shared);
impl Temp {
    fn new() -> Self {
        // Generated by the independent writer; it contains four opaque packets,
        // so reader tests do not depend on any codec or native libraries.
        let value: serde_json::Value =
            serde_json::from_str(include_str!("../../../../data/mp4-reader-fixture.json")).unwrap();
        let hex = value["hex"].as_str().unwrap();
        let raw: Vec<u8> = (0..hex.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
            .collect();
        Self(Shared::new(&raw))
    }
    fn open(&self) -> Mp4Reader<Shared> {
        Mp4Reader::new(self.0.clone()).unwrap()
    }

    fn append_sample_group(&self, tag: &[u8; 4]) -> u64 {
        let structure = scan(&mut self.0.clone(), OpenMode::Verified).unwrap();
        let original = structure.get(tag).unwrap();
        let stbl = structure.get(b"stbl").unwrap();
        let mut raw = self.0.bytes();
        let mut extra = raw[original.offset as usize..original.end as usize].to_vec();
        let grouping_type = (original.data - original.offset + 4) as usize;
        extra[grouping_type..grouping_type + 4].copy_from_slice(b"roll");
        if tag == b"sgpd" {
            let end = extra.len();
            extra[end - 2..].copy_from_slice(&(-1i16).to_be_bytes());
        }
        // This fixture has moov after mdat, so appending metadata does not move audio.
        for a in structure.boxes.values() {
            if a.offset <= stbl.offset && a.end >= stbl.end {
                assert_eq!(a.data - a.offset, 8);
                let size = u32::try_from(a.end - a.offset + extra.len() as u64).unwrap();
                raw[a.offset as usize..a.offset as usize + 4].copy_from_slice(&size.to_be_bytes());
            }
        }
        raw.splice(stbl.end as usize..stbl.end as usize, extra);
        self.0.replace(raw);
        stbl.end + grouping_type as u64
    }
}
#[test]
fn stream_and_verify() {
    let temp = Temp::new();
    let mut reader = temp.open();
    assert!(!reader.summary().verified);
    for i in 0..4 {
        let packet = reader.next_packet().unwrap().unwrap();
        assert_eq!((packet.index, packet.raw_frame), (i, 1024 * i));
        assert_eq!(packet.bytes, [i as u8; 4]);
    }
    assert!(reader.next_packet().unwrap().is_none());
    assert!(reader.summary().verified);
}
#[test]
fn audio_mutation_cannot_pass_short_read_verification() {
    let temp = Temp::new();
    let mut reader = temp.open();
    let offset = reader
        .index
        .next(&mut reader.file, reader.structure.bytes)
        .unwrap()
        .unwrap()
        .0;
    reader.index = Index::open(&mut reader.file, &reader.structure, OpenMode::Verified).unwrap();
    temp.0.change(offset + 1, &[255]);
    assert!(reader.verify_remaining().is_err());
    assert!(!reader.summary().verified);
}
#[test]
fn metadata_mutation_after_audio_read_is_rejected() {
    let temp = Temp::new();
    let mut reader = temp.open();
    for _ in 0..4 {
        reader.next_packet().unwrap().unwrap();
    }
    let offset = reader.structure.get(b"mvhd").unwrap().data + 5;
    temp.0.change(offset, &[1]);
    assert!(reader.next_packet().is_err());
}

#[test]
fn repeated_sample_group_payloads_are_checked_even_with_unchanged_mtime() {
    for tag in [b"sgpd", b"sbgp"] {
        let temp = Temp::new();
        let offset = temp.append_sample_group(tag);
        let mut reader = temp.open();
        let name = std::str::from_utf8(tag).unwrap();
        let summary = reader.summary();
        let count = if name == "sgpd" {
            summary.sgpd_count
        } else {
            summary.sbgp_count
        };
        assert_eq!(count, 2);
        let before = reader.structure.modified;
        temp.0.change_quietly(offset, b"x");
        assert_eq!(temp.0.clone().revision().unwrap(), before);
        assert!(reader.verify_remaining().is_err());
        assert!(!reader.summary().verified);
    }
}
#[test]
fn append_and_truncate_are_rejected_after_initial_scan() {
    for truncate in [false, true] {
        let temp = Temp::new();
        let mut reader = temp.open();
        if truncate {
            temp.0.truncate(16);
        } else {
            let end = temp.0.bytes().len() as u64;
            temp.0.change(end, &[0; 8]);
        }
        assert!(reader.verify_remaining().is_err());
    }
}

#[test]
fn a_rewound_pass_repeats_the_samples_and_is_verified_again() {
    let temp = Temp::new();
    let mut reader = temp.open();
    let mut first = vec![];
    while let Some(packet) = reader.next_packet().unwrap() {
        first.push(packet);
    }
    let summary = reader.summary();
    assert!(summary.verified);
    reader.rewind().unwrap();
    assert!(!reader.summary().verified);
    let mut second = vec![];
    while let Some(packet) = reader.next_packet().unwrap() {
        second.push(packet);
    }
    assert_eq!(first, second);
    let again = reader.summary();
    assert!(again.verified);
    assert_eq!(
        (again.audio_sha256, again.packets_sha256),
        (summary.audio_sha256, summary.packets_sha256)
    );
    reader.rewind().unwrap();
    let offset = reader.structure.get(b"mvhd").unwrap().data + 5;
    temp.0.change(offset, &[1]);
    assert!(reader.verify_remaining().is_err());
}
