use super::*;
use std::{
    fs::{self, FileTimes, OpenOptions},
    io::{Seek, SeekFrom, Write},
    sync::atomic::{AtomicU64, Ordering},
};
static NEXT: AtomicU64 = AtomicU64::new(0);
struct Temp(std::path::PathBuf);
impl Temp {
    fn new() -> Self {
        let p = std::env::temp_dir().join(format!(
            "apac-mp4-{}-{}.mp4",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        ));
        // Generated by the independent writer; it contains four opaque packets,
        // so reader tests do not depend on any codec or native libraries.
        let value: Value =
            serde_json::from_str(include_str!("../../data/mp4-reader-fixture.json")).unwrap();
        let hex = value["hex"].as_str().unwrap();
        let raw: Vec<u8> = (0..hex.len())
            .step_by(2)
            .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
            .collect();
        fs::write(&p, raw).unwrap();
        Self(p)
    }

    fn append_sample_group(&self, tag: &[u8; 4]) -> u64 {
        let structure = scan(&mut File::open(&self.0).unwrap()).unwrap();
        let original = structure.get(tag).unwrap();
        let stbl = structure.get(b"stbl").unwrap();
        let mut raw = fs::read(&self.0).unwrap();
        let mut extra = raw[original.offset as usize..original.end as usize].to_vec();
        let grouping_type = (original.data - original.offset + 4) as usize;
        extra[grouping_type..grouping_type + 4].copy_from_slice(b"roll");
        if tag == b"sgpd" {
            let end = extra.len();
            extra[end - 2..].copy_from_slice(&(-1i16).to_be_bytes());
        }
        // This fixture has moov after mdat, so appending metadata does not move audio.
        for a in structure.boxes.values() {
            if a.offset <= stbl.offset && a.end >= stbl.end {
                assert_eq!(a.data - a.offset, 8);
                let size = u32::try_from(a.end - a.offset + extra.len() as u64).unwrap();
                raw[a.offset as usize..a.offset as usize + 4].copy_from_slice(&size.to_be_bytes());
            }
        }
        raw.splice(stbl.end as usize..stbl.end as usize, extra);
        fs::write(&self.0, raw).unwrap();
        stbl.end + grouping_type as u64
    }
}
impl Drop for Temp {
    fn drop(&mut self) {
        let _ = fs::remove_file(&self.0);
    }
}
#[test]
fn stream_and_verify() {
    let temp = Temp::new();
    let mut reader = Mp4Reader::open(&temp.0).unwrap();
    assert!(!reader.report()["consistency_verified"].as_bool().unwrap());
    for i in 0..4 {
        let (n, t, raw) = reader.next_packet().unwrap().unwrap();
        assert_eq!((n, t), (i, 1024 * i));
        assert_eq!(raw, [i as u8; 4]);
    }
    assert!(reader.next_packet().unwrap().is_none());
    assert_eq!(reader.report()["consistency_verified"], true);
}
#[test]
fn audio_mutation_cannot_pass_short_read_verification() {
    let temp = Temp::new();
    let mut reader = Mp4Reader::open(&temp.0).unwrap();
    let offset = reader
        .index
        .next(&mut reader.file, reader.structure.bytes)
        .unwrap()
        .unwrap()
        .0;
    reader.index = Index::open(&mut reader.file, &reader.structure).unwrap();
    let mut file = OpenOptions::new().write(true).open(&temp.0).unwrap();
    file.seek(SeekFrom::Start(offset + 1)).unwrap();
    file.write_all(&[255]).unwrap();
    assert!(reader.verify_remaining().is_err());
    assert_eq!(reader.report()["consistency_verified"], false);
}
#[test]
fn metadata_mutation_after_audio_read_is_rejected() {
    let temp = Temp::new();
    let mut reader = Mp4Reader::open(&temp.0).unwrap();
    for _ in 0..4 {
        reader.next_packet().unwrap().unwrap();
    }
    let offset = reader.structure.get(b"mvhd").unwrap().data + 5;
    let mut file = OpenOptions::new().write(true).open(&temp.0).unwrap();
    file.seek(SeekFrom::Start(offset)).unwrap();
    file.write_all(&[1]).unwrap();
    assert!(reader.next_packet().is_err());
}

#[test]
fn repeated_sample_group_payloads_are_checked_even_with_unchanged_mtime() {
    for tag in [b"sgpd", b"sbgp"] {
        let temp = Temp::new();
        let offset = temp.append_sample_group(tag);
        let mut reader = Mp4Reader::open(&temp.0).unwrap();
        let name = std::str::from_utf8(tag).unwrap();
        assert_eq!(reader.report()["sample_group_box_counts"][name], 2);
        let mut file = OpenOptions::new().write(true).open(&temp.0).unwrap();
        file.seek(SeekFrom::Start(offset)).unwrap();
        file.write_all(b"x").unwrap();
        file.set_times(FileTimes::new().set_modified(reader.structure.modified.unwrap()))
            .unwrap();
        assert_eq!(
            file.metadata().unwrap().modified().unwrap(),
            reader.structure.modified.unwrap()
        );
        assert!(reader.verify_remaining().is_err());
        assert_eq!(reader.report()["consistency_verified"], false);
    }
}
#[test]
fn append_and_truncate_are_rejected_after_initial_scan() {
    for truncate in [false, true] {
        let temp = Temp::new();
        let mut reader = Mp4Reader::open(&temp.0).unwrap();
        let mut file = OpenOptions::new().write(true).open(&temp.0).unwrap();
        if truncate {
            file.set_len(16).unwrap();
        } else {
            file.seek(SeekFrom::End(0)).unwrap();
            file.write_all(&[0; 8]).unwrap();
        }
        assert!(reader.verify_remaining().is_err());
    }
}
