#!/usr/bin/env python3
"""Hash-bound HOA wire dictionaries shared by the encoder and decoder.

Research verifier only. Rust builds use the committed, pointer-free tables.
The unitary matrices are format dictionaries, not numerical approximations
generated by the decoder. Their original Float32 bit patterns are preserved.
"""
import argparse
import hashlib
import json
from pathlib import Path
import struct
from hoa_salient_format import format_name, shared_name, load_format, split_format, json_bytes
from generate_hoa_salient_measured import load_measurements, measured_book, replace_book
from generate_hoa_salient_measured_matrix import load_measurements as load_matrix_measurements, measured_matrix, replace_matrix
from generate_hoa_salient_measured_groups import GROUP_USERS, load_measurements as load_group_measurements, replace_group
from generate_hoa_salient_measured import measured_group

COMPONENT_SHA256 = '826948774145d657788f3101cf36ad1103c230e9bb3712cb65bc56763fd297dd'
ROOT = Path(__file__).resolve().parents[1]


def reader(path):
    raw = path.read_bytes()
    if hashlib.sha256(raw).hexdigest() != COMPONENT_SHA256:
        raise ValueError('unverified AudioCodecs component')
    for i in range(struct.unpack_from('>I', raw, 4)[0]):
        cpu, _, offset, size, _ = struct.unpack_from('>IIIII', raw, 8 + 20*i)
        if cpu == 0x1000007:
            break
    else:
        raise ValueError('missing verified x86_64 slice')
    data = memoryview(raw)[offset:offset+size]
    position, segments = 32, []
    for _ in range(struct.unpack_from('<I', data, 16)[0]):
        command, length = struct.unpack_from('<II', data, position)
        if command == 0x19:
            _, va, _, file_offset, file_size = struct.unpack_from('<16sQQQQ', data, position+8)
            segments.append((va, file_offset, file_size))
        position += length

    def read(address, size):
        for va, file_offset, file_size in segments:
            if va <= address and address+size <= va+file_size:
                return bytes(data[file_offset+address-va:file_offset+address-va+size])
        raise ValueError('data outside verified segments')
    return read


def extract(path, order=3, quantization_bits=6):
    if order not in range(1,11) or quantization_bits not in range(6,10):
        raise ValueError('spatial dictionary key outside order 1..10 / precision 6..9')
    coefficients=(order+1)**2
    read = reader(path)
    def pointer(address):
        return struct.unpack('<Q', read(address, 8))[0] & 0xffffffffff
    def spans(address):
        begin, end = pointer(address), pointer(address+8)
        assert (end-begin) % 16 == 0 and end-begin <= 64
        return [(pointer(p), pointer(p+8)) for p in range(begin, end, 16)]
    modes = []
    for mode in range(6):
        address = pointer(0xaaa990+(order-1)*32+(quantization_bits-6)*8) + mode*56
        groups = [list(struct.unpack('<'+'H'*((end-begin)//2), read(begin, end-begin)))
                  for begin, end in spans(address+16)]
        books = []
        for begin, end in spans(address):
            assert end-begin == (1<<quantization_bits)*9
            book = [list(struct.unpack('<BQ', read(begin+value*9, 9))) for value in range(1<<quantization_bits)]
            assert all(1 <= length <= 32 and code < 1 << length for length, code in book)
            books.append(book)
        matrices = []
        for begin, end in spans(address+32):
            assert end-begin == coefficients*coefficients*4
            matrices.append(list(struct.unpack('<'+'I'*(coefficients*coefficients), read(begin, end-begin))))
        modes.append(dict(mode=mode, groups=groups, codebooks=books,
                          signs=bool(read(address+48, 1)[0]), matrices_f32=matrices))
    values = dict(order=order, quantization_bits=quantization_bits, modes=modes)
    digest = hashlib.sha256(json.dumps(values, sort_keys=True, separators=(',', ':')).encode()).hexdigest()
    result = dict(schema_version=1, format_profile=(f'apac-hoa-salient-order{order}-q{quantization_bits}-format-v1' if quantization_bits!=6 else f'apac-hoa-salient-order{order}-format-v1' if order!=3 else 'apac-hoa-salient-format-v1'),
                source=dict(component='AudioCodecs 7.0', component_sha256=COMPONENT_SHA256,
                            architecture='x86_64', method='shared spatial encoder/decoder wire dictionaries'),
                tables_sha256=digest, **values)
    if order == 3:
        for measurement in load_measurements(quantization_bits):
            mode, book = measurement['mode'], measurement['book']
            if result['modes'][mode]['codebooks'][book] != measured_book(measurement):
                raise ValueError(f'reference differs from measured codebook {mode}/{book}')
            result = replace_book(result, measurement)
    if order == 3:
        for measurement in load_matrix_measurements():
            cluster = measurement['cluster']
            if result['modes'][4]['matrices_f32'][cluster] != measured_matrix(measurement):
                raise ValueError(f'reference differs from measured mode-4 cluster-{cluster} matrix')
            result = replace_matrix(result, measurement)
        for measurement in load_group_measurements():
            key = (measurement['mode'], measurement['book'])
            for mode, group in GROUP_USERS[key]:
                if result['modes'][mode]['groups'][group] != measured_group(measurement):
                    raise ValueError(f'reference differs from measured coefficient group {mode}/{group}')
            result = replace_group(result, measurement)
    return result


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--component', type=Path, default=Path('/System/Library/Components/AudioCodecs.component/Contents/MacOS/AudioCodecs'))
    p.add_argument('--order', type=int, choices=range(1,11), default=3)
    p.add_argument('--quantization-bits',type=int,choices=range(6,10),default=6)
    p.add_argument('--table', type=Path)
    p.add_argument('--write', action='store_true')
    a = p.parse_args(); result = extract(a.component,a.order,a.quantization_bits)
    if a.table is None:
        a.table=ROOT/'data'/format_name(a.order,a.quantization_bits)
    if a.write:
        stored, shared = split_format(result)
        shared_path = a.table.with_name(shared_name(a.order))
        raw_shared = json_bytes(shared)
        if a.table.exists():
            raise FileExistsError(a.table)
        if shared_path.exists():
            if shared_path.read_bytes() != raw_shared:
                raise ValueError('existing shared HOA dictionaries differ')
        else:
            with shared_path.open('xb') as f:
                f.write(raw_shared)
        with a.table.open('xb') as f:
            f.write(json_bytes(stored))
    else:
        assert load_format(a.table) == result, 'HOA dictionaries differ'
    print(json.dumps(dict(tables_sha256=result['tables_sha256'], modes=6, codebooks=8, transforms=4)))


if __name__ == '__main__':
    main()
