#!/usr/bin/env python3
"""Hash-bound HOA wire dictionaries shared by the encoder and decoder.

Research verifier only. Rust builds use the committed, pointer-free tables.
The unitary matrices are format dictionaries, not numerical approximations
generated by the decoder. Their original Float32 bit patterns are preserved.
"""
import argparse
import hashlib
import json
from pathlib import Path
import struct

COMPONENT_SHA256 = '826948774145d657788f3101cf36ad1103c230e9bb3712cb65bc56763fd297dd'
ROOT = Path(__file__).resolve().parents[1]


def reader(path):
    raw = path.read_bytes()
    if hashlib.sha256(raw).hexdigest() != COMPONENT_SHA256:
        raise ValueError('unverified AudioCodecs component')
    for i in range(struct.unpack_from('>I', raw, 4)[0]):
        cpu, _, offset, size, _ = struct.unpack_from('>IIIII', raw, 8 + 20*i)
        if cpu == 0x1000007:
            break
    else:
        raise ValueError('missing verified x86_64 slice')
    data = memoryview(raw)[offset:offset+size]
    position, segments = 32, []
    for _ in range(struct.unpack_from('<I', data, 16)[0]):
        command, length = struct.unpack_from('<II', data, position)
        if command == 0x19:
            _, va, _, file_offset, file_size = struct.unpack_from('<16sQQQQ', data, position+8)
            segments.append((va, file_offset, file_size))
        position += length

    def read(address, size):
        for va, file_offset, file_size in segments:
            if va <= address and address+size <= va+file_size:
                return bytes(data[file_offset+address-va:file_offset+address-va+size])
        raise ValueError('data outside verified segments')
    return read


def extract(path):
    read = reader(path)
    def pointer(address):
        return struct.unpack('<Q', read(address, 8))[0] & 0xffffffffff
    def spans(address):
        begin, end = pointer(address), pointer(address+8)
        assert (end-begin) % 16 == 0 and end-begin <= 64
        return [(pointer(p), pointer(p+8)) for p in range(begin, end, 16)]
    modes = []
    for mode in range(6):
        address = 0xaa7f90 + mode*56
        groups = [list(struct.unpack('<'+'H'*((end-begin)//2), read(begin, end-begin)))
                  for begin, end in spans(address+16)]
        books = []
        for begin, end in spans(address):
            assert end-begin == 64*9
            book = [list(struct.unpack('<BQ', read(begin+value*9, 9))) for value in range(64)]
            assert all(1 <= length <= 32 and code < 1 << length for length, code in book)
            books.append(book)
        matrices = []
        for begin, end in spans(address+32):
            assert end-begin == 16*16*4
            matrices.append(list(struct.unpack('<256I', read(begin, 1024))))
        modes.append(dict(mode=mode, groups=groups, codebooks=books,
                          signs=bool(read(address+48, 1)[0]), matrices_f32=matrices))
    values = dict(order=3, quantization_bits=6, modes=modes)
    digest = hashlib.sha256(json.dumps(values, sort_keys=True, separators=(',', ':')).encode()).hexdigest()
    return dict(schema_version=1, format_profile='apac-hoa-salient-format-v1',
                source=dict(component='AudioCodecs 7.0', component_sha256=COMPONENT_SHA256,
                            architecture='x86_64', method='shared spatial encoder/decoder wire dictionaries'),
                tables_sha256=digest, **values)


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--component', type=Path, default=Path('/System/Library/Components/AudioCodecs.component/Contents/MacOS/AudioCodecs'))
    p.add_argument('--table', type=Path, default=ROOT/'data/hoa-salient-format-v1.json')
    p.add_argument('--write', action='store_true')
    a = p.parse_args(); result = extract(a.component)
    raw = (json.dumps(result, indent=2)+'\n').encode()
    if a.write:
        with a.table.open('xb') as f:
            f.write(raw)
    else:
        assert a.table.read_bytes() == raw, 'HOA dictionaries differ'
    print(json.dumps(dict(tables_sha256=result['tables_sha256'], modes=6, codebooks=8, transforms=4)))


if __name__ == '__main__':
    main()
